name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_REPO: isd-sgcu/rnkm65-gitOps
  GITOPS_DIR: environment/dev/gateway

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: ${{ env.GITOPS_DIR }}
          ssh-key: ${{ secrets.GITOPS_SSH_KEY }}

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Set image
        run: |
          kustomize edit set image ${{ env.IMAGE_NAME }}=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          git add .
          git commit -m "Set image tag to `${{ env.IMAGE_TAG }}`"
          git push
